# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.1
language: swift
# cache: cocoapods
podfile: Example/Podfile
gemfile: Example/Gemfile

before_install:
- bundle update
- bundle install

script:
- bundle exec fastlane ios test
- bundle exec pod lib lint
